target: TARGET

numeric_features:
  - AMT_INCOME_TOTAL
  - AMT_CREDIT
  - AMT_ANNUITY
  - AMT_GOODS_PRICE
  - AGE_YEARS
  - EMPLOYMENT_YEARS
  - CREDIT_TO_INCOME_RATIO
  - ANNUITY_TO_INCOME_RATIO
  - ANNUITY_TO_CREDIT_RATIO

categorical_features:
  - CODE_GENDER
  - NAME_FAMILY_STATUS
  - NAME_EDUCATION_TYPE
  - NAME_INCOME_TYPE
  - OCCUPATION_TYPE
  - NAME_HOUSING_TYPE
  - FLAG_OWN_CAR
  - FLAG_OWN_REALTY
